const Data = [{
    "success": true,
    "data": [
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "raw",
            "child_product_id": 131,
            "child_name": "Cabbage Local",
            "qty": "5.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.005000",
            "final_qty": "0.005000",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 0.0093
        },
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "raw",
            "child_product_id": 250,
            "child_name": "Cod Fish Fz",
            "qty": "60.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.060000",
            "final_qty": "0.060000",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 3.9251
        },
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "raw",
            "child_product_id": 258,
            "child_name": "Coriander Fresh",
            "qty": "5.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.005000",
            "final_qty": "0.005000",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 0.0371
        },
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "raw",
            "child_product_id": 263,
            "child_name": "Corn Tortilla Fresh",
            "qty": "1.00",
            "unit_selected": "26",
            "unit_selected_name": "1.00Ea",
            "base_unit_name": "1.00Ea",
            "base_unit_coverted": "1.000000",
            "final_qty": "1.000000",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 0.9378
        },
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "raw",
            "child_product_id": 528,
            "child_name": "Lime",
            "qty": "10.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.010000",
            "final_qty": "0.010000",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 0.0415
        },
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "batch",
            "child_product_id": 2516,
            "child_name": "Scotch Bonnet Mayo",
            "qty": "5.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "16.20Kg",
            "base_unit_coverted": "0.000300",
            "final_qty": "0.000300",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 0.0713
        },
        {
            "parent_id": 2516,
            "parent_name": "Scotch Bonnet Mayo",
            "product_type": "raw",
            "child_product_id": 138,
            "child_name": "Capers In Brine",
            "qty": "0.95",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.950000",
            "final_qty": "0.000285",
            "level": 1,
            "path": "1pc Fish Taco > Capers In Brine (0.000285)",
            "cost": 0.011
        },
        {
            "parent_id": 2516,
            "parent_name": "Scotch Bonnet Mayo",
            "product_type": "raw",
            "child_product_id": 414,
            "child_name": "Habanero Scotch Bonnet Chilli",
            "qty": "0.30",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.300000",
            "final_qty": "0.000090",
            "level": 1,
            "path": "1pc Fish Taco > Habanero Scotch Bonnet Chilli (0.000090)",
            "cost": 0.0072
        },
        {
            "parent_id": 2516,
            "parent_name": "Scotch Bonnet Mayo",
            "product_type": "raw",
            "child_product_id": 574,
            "child_name": "Mayo HelmanS Real 378Lt",
            "qty": "15.12",
            "unit_selected": "15",
            "unit_selected_name": "1.00Lt",
            "base_unit_name": "1.00Lt",
            "base_unit_coverted": "15.120000",
            "final_qty": "0.004536",
            "level": 1,
            "path": "1pc Fish Taco > Mayo HelmanS Real 378Lt (0.004536)",
            "cost": 0.0499
        },
        {
            "parent_id": 2516,
            "parent_name": "Scotch Bonnet Mayo",
            "product_type": "raw",
            "child_product_id": 913,
            "child_name": "Vegetable Powder Knorr",
            "qty": "0.23",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.230000",
            "final_qty": "0.000069",
            "level": 1,
            "path": "1pc Fish Taco > Vegetable Powder Knorr (0.000069)",
            "cost": 0.0032
        },
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "batch",
            "child_product_id": 2737,
            "child_name": "Fish Beer Taco Batter",
            "qty": "15.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.015000",
            "final_qty": "0.015000",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 0.0321
        },
        {
            "parent_id": 2737,
            "parent_name": "Fish Beer Taco Batter",
            "product_type": "raw",
            "child_product_id": 60,
            "child_name": "Baking Powder",
            "qty": "40.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.040000",
            "final_qty": "0.000600",
            "level": 1,
            "path": "1pc Fish Taco > Baking Powder (0.000600)",
            "cost": 0.0064
        },
        {
            "parent_id": 2737,
            "parent_name": "Fish Beer Taco Batter",
            "product_type": "raw",
            "child_product_id": 341,
            "child_name": "Flour All Purpose T45",
            "qty": "255.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.255000",
            "final_qty": "0.003825",
            "level": 1,
            "path": "1pc Fish Taco > Flour All Purpose T45 (0.003825)",
            "cost": 0.0153
        },
        {
            "parent_id": 2737,
            "parent_name": "Fish Beer Taco Batter",
            "product_type": "raw",
            "child_product_id": 766,
            "child_name": "Salt Iodized Nezo Satl Fine",
            "qty": "8.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.008000",
            "final_qty": "0.000120",
            "level": 1,
            "path": "1pc Fish Taco > Salt Iodized Nezo Satl Fine (0.000120)",
            "cost": 0.0003
        },
        {
            "parent_id": 2737,
            "parent_name": "Fish Beer Taco Batter",
            "product_type": "raw",
            "child_product_id": 838,
            "child_name": "Sugar Granulated",
            "qty": "4.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.004000",
            "final_qty": "0.000060",
            "level": 1,
            "path": "1pc Fish Taco > Sugar Granulated (0.000060)",
            "cost": 0.0002
        },
        {
            "parent_id": 2737,
            "parent_name": "Fish Beer Taco Batter",
            "product_type": "raw",
            "child_product_id": 1353,
            "child_name": "All Purpose Flour",
            "qty": "255.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.255000",
            "final_qty": "0.003825",
            "level": 1,
            "path": "1pc Fish Taco > All Purpose Flour (0.003825)",
            "cost": 0.0099
        },
        {
            "parent_id": null,
            "parent_name": null,
            "product_type": "batch",
            "child_product_id": 2922,
            "child_name": "Escovitch Pickle",
            "qty": "10.00",
            "unit_selected": "27",
            "unit_selected_name": "1.00Gr",
            "base_unit_name": "20.00Kg",
            "base_unit_coverted": "0.000500",
            "final_qty": "0.000500",
            "level": 0,
            "path": "1pc Fish Taco",
            "cost": 0.1558
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 12,
            "child_name": "All Spice Pwdr Pimento",
            "qty": "0.05",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.050000",
            "final_qty": "0.000025",
            "level": 1,
            "path": "1pc Fish Taco > All Spice Pwdr Pimento (0.000025)",
            "cost": 0.0009
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 148,
            "child_name": "Carrot",
            "qty": "4.00",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "4.000000",
            "final_qty": "0.002000",
            "level": 1,
            "path": "1pc Fish Taco > Carrot (0.002000)",
            "cost": 0.0075
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 414,
            "child_name": "Habanero Scotch Bonnet Chilli",
            "qty": "2.00",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "2.000000",
            "final_qty": "0.001000",
            "level": 1,
            "path": "1pc Fish Taco > Habanero Scotch Bonnet Chilli (0.001000)",
            "cost": 0.08
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 651,
            "child_name": "Onion White",
            "qty": "6.00",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "6.000000",
            "final_qty": "0.003000",
            "level": 1,
            "path": "1pc Fish Taco > Onion White (0.003000)",
            "cost": 0.0135
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 759,
            "child_name": "S Chayote",
            "qty": "1.50",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "1.500000",
            "final_qty": "0.000750",
            "level": 1,
            "path": "1pc Fish Taco > S Chayote (0.000750)",
            "cost": 0.0158
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 766,
            "child_name": "Salt Iodized Nezo Satl Fine",
            "qty": "0.50",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.500000",
            "final_qty": "0.000250",
            "level": 1,
            "path": "1pc Fish Taco > Salt Iodized Nezo Satl Fine (0.000250)",
            "cost": 0.0007
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 838,
            "child_name": "Sugar Granulated",
            "qty": "0.50",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.500000",
            "final_qty": "0.000250",
            "level": 1,
            "path": "1pc Fish Taco > Sugar Granulated (0.000250)",
            "cost": 0.0008
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 879,
            "child_name": "Thyme Fresh",
            "qty": "0.50",
            "unit_selected": "1",
            "unit_selected_name": "1.00Kg",
            "base_unit_name": "1.00Kg",
            "base_unit_coverted": "0.500000",
            "final_qty": "0.000250",
            "level": 1,
            "path": "1pc Fish Taco > Thyme Fresh (0.000250)",
            "cost": 0.015
        },
        {
            "parent_id": 2922,
            "parent_name": "Escovitch Pickle",
            "product_type": "raw",
            "child_product_id": 926,
            "child_name": "Vinegar White",
            "qty": "19.00",
            "unit_selected": "15",
            "unit_selected_name": "1.00Lt",
            "base_unit_name": "1.00Lt",
            "base_unit_coverted": "19.000000",
            "final_qty": "0.009500",
            "level": 1,
            "path": "1pc Fish Taco > Vinegar White (0.009500)",
            "cost": 0.0216
        },
       
    ]
}]
export default Data;